require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'bin/**/*'
    - vendor/bundle/**/*

Documentation:
  Enabled: false
