default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5  %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  port: 5432

development:
  <<: *default
  database: booking_api_development
  
test:
  <<: *default
  database: booking_api_test

production:
  <<: *default
  database: booking_api_production
  username: booking_api
  password: <%= ENV['BOOKING_API_DATABASE_PASSWORD'] %>
